# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andrew V. Subach
title: Software Engineer
email: subachandrew@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: andrewsubie
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: andrew-subach
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: channel/UC5WuqCUWn7ryBcFUWpI5PDA
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: My Old Website
  icon: fas fa-globe
  url: https://www.asubach.w3.uvm.edu
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Andrew and I'm a driven software engineer, tinkerer and lifelong learner. Recently, I graduated from UVM where my experiences spanned machine learning, software development and renewable energy systems. Proficient in Python, skilled in Git, CLI, containerized environments, SQL and data analysis. I excel at developing efficient, practical solutions to complex problems and collaborating to achieve project goals.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Leveraging Evolutionary Computation to Solve for Polynomial Roots
        link: github.com/andrewsubie/evol-comp-final
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Developed evolutionary computation algorithms with diversity maintenance to generate and optimize polynomial root-solving formulas.
        description: | # this will include new lines to allow paragraphs
          I completed this project as part of an Evolutionary Computation class during the fall semester of my senior year at UVM. What began as a final project for the class quickly grew in scope and was an invaluable experience in both computing and project management. During this project, I created a custom data structure inspired by Compositional Pattern Producing Networks (CCPNs) to represent algebraic formulae. Furthermore, I had foundational lessons about the importance data integrity and data version control for machine learning efforts.  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Vermont
        caption: 2021 - 2025
        sub_title: B.S in Computer Science, Minor in Mathematics
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data and software engineering some of my other interests and hobbies are:
      - Running
      - Backcountry Skiing
      - Reading
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
